package dk.mosberg.tab.client.datagen.provider;

import java.util.concurrent.CompletableFuture;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.DataWriter;

public final class TABBlockStateProvider implements DataProvider {
    public TABBlockStateProvider(FabricDataOutput output) {
        // Intentionally no-op: blockstates are generated by TABAssetsProvider.
    }

    @Override
    public CompletableFuture<?> run(DataWriter writer) {
        return CompletableFuture.completedFuture(null);
    }

    @Override
    public String getName() {
        return "TABBlockStateProvider (noop)";
    }
}
